lib.name = button_gesture_model
class.sources = button_gesture_model.cpp
cflags = -std=c++20 -I'../first_button_gesture_model' -I'./pfr/include' -I '../../../../' -I'../../../../dependencies/pfr/include'
include pd-lib-builder/Makefile.pdlibbuilder
